// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiygxyjubvbdgdrqndec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeWd4eWp1YnZiZGdkcnFuZGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDY0MjgsImV4cCI6MjA3MDYyMjQyOH0.v97uvrHEUeb0dFdh0aYFD8k-WMdZPrHTTSd2G60xgK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});